// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
	_ "embed"

	"github.com/swaggo/swag"
)

//go:embed swagger.yaml
var swaggerYAML string

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "PR Reviewer Assignment Service",
	Description:      "Сервис для автоматического назначения ревьюверов на Pull Request'ы",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  swaggerYAML,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
